name: Reusable build workflow

on:  
  workflow_call:
    inputs:
      runs_on:
        description: 'The runner to run on'
        required: true
        type: string
        default: 'ubuntu-22.04'
      platform:
        description: 'The buildx platform'
        required: true
        type: string
        default: 'linux/amd64'
      tag:
        description: 'The docker tag to add for the platform'
        required: true
        type: string
        default: 'amd64'
      version:
        description: 'The Kodi version'
        required: true
        type: string
        default: '20.0'
      codename:
        description: 'The Kodi codename'
        required: true
        type: string
        default: 'Nexus'
      cflags:
        description: 'C and CXX flags for cmake'
        type: string
        default: ''
      with_cpu:
        description: '-DWITH_CPU for cmake'
        type: string
        default: ''

jobs:
  build:
    runs-on: ${{ inputs.runs_on }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: ${{ inputs.platform }}
          build-args: |
              BASE_IMAGE=ubuntu:22.04
              EASY_NOVNC_IMAGE=fhriley/easy-novnc:1.3.0
              PYTHON_VERSION=3.10
              KODI_BRANCH=${{ inputs.version }}-${{ inputs.codename }}
              CFLAGS=${{ inputs.cflags }}
              CXXFLAGS=${{ inputs.cflags }}
              WITH_CPU=${{ inputs.with_cpu }}
          tags: e2pluginss/kodi-headless-novnc:${{ inputs.version }}-${{ inputs.tag }}
          cache-from: type=registry,ref=e2pluginss/kodi-headless-novnc:cache-${{ inputs.codename }}-${{ inputs.tag }}
          cache-to: type=registry,mode=max,ref=e2pluginss/kodi-headless-novnc:cache-${{ inputs.codename }}-${{ inputs.tag }}
